on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      languagetool:
        image: silviof/docker-languagetool
        options: --rm -p 8010:8010 
        ports: 
          - 8010:8010
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check DB
        uses: slftool/Action@v3
      - uses: actions/upload-artifact@v2
        with:
          name: errorlog
          path: errorlog.txt
