on: [push]

jobs:
  check-db:
    runs-on: ubuntu-latest
    services:
      languagetool:
        image: silviof/docker-languagetool
        ports: 
          - 8010:8010
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check DB
        uses: slftool/Action@v3
      - uses: actions/upload-artifact@v2
        with:
          name: errorlog
          path: errorlog.txt
